version: "3.7"
services:
  postgres:
    image: postgres:12.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker